### ISSUE TITLE
There seems to be a small bug with the jpeg format

### ISSUE THREAD

**Issue by DaanBiesterbos** [josealejandro2928/react-image-picker-editor#1]
Impressive work! 👍 

I noticed that when I select jpeg and download the file I get a jjif file. Seems to be a small bug?

Also, when using the cropper with aspect ratio enabled, I would expect the aspect ratio to apply to the cropping area. 
As is the case here: https://jamesooi.design/Croppr.js/
Right now the aspect ratio seems to be related to the viewport I think? 
Just a suggestion.

Thank you for sharing.

Daan

**Comment by josealejandro2928** [comment]
Thanks for your comment, I just tried to reproduce the jpeg format problem, but it never seems to happen, I try in Mozilla and Chrome but the image always downloads fine. With
![Screenshot from 2022-04-01 06-00-11](https://user-images.githubusercontent.com/37028825/161192849-951de177-d5da-4847-8af9-6f14d0d91e49.png)
![Screenshot from 2022-04-01 05-48-39](https://user-images.githubusercontent.com/37028825/161192855-6a6caa3b-c8b0-40a6-879c-ea6b4cd462cd.png)
![Screenshot from 2022-04-01 05-48-15](https://user-images.githubusercontent.com/37028825/161192860-a66efef6-7f2a-4ea5-8a79-d76c45ca3386.png)
 respect to the crop, right now it disconnected from the aspect ratio part. I just crap the image inside the square of the cropper.

**Comment by josealejandro2928** [comment]
I have reimplemented the cropper, now it's better, and works pret well on mobile. I haven't seen any problem with the download feature. Thanks for your feedback.

**Comment by DaanBiesterbos** [comment]
Hmm I was working on my Windows  laptop.  I was using Chrome or Edge. I did
try to switch to png (that worked) and then back to jpeg and I got the jjif
again. I will  see if I can reproduce the issue later tonight. I will check
out the console log. Perhaps it is a browser thing.

Op vr 1 apr. 2022 06:04 schreef Jose Alejandro Concepción Álvarez <
***@***.***>:
