### ISSUE TITLE
Error loading the src on imageSrcProp

### ISSUE THREAD

**Issue by BilawalSh** [josealejandro2928/react-image-picker-editor#10]
Hello @josealejandro2928 @Lucas-Jav I have found this issue when we pass the image URL it shows an error 

![image](https://github.com/josealejandro2928/react-image-picker-editor/assets/59328380/0cb836c9-86fb-43d8-a440-ebdc813f3f17)

I try many ways but still get this error on all images url.

Can you fix it?

**Comment by BilawalSh** [comment]
Can you check it soon?

**Comment by Lucas-Jav** [comment]
What version are you using, and are you on react or next?

**Comment by Lucas-Jav** [comment]
In fact, I think I already discovered the error, you are passing a url to the src, the src is for images in base64, it does not accept images in url
![image](https://github.com/josealejandro2928/react-image-picker-editor/assets/81967127/c90d27a4-39be-4292-8212-15ab0ab9a466)

**Comment by josealejandro2928** [comment]
That is not an error, the package allows to load a image as url or as base64. For its internal behavio0r it always try to parse and convert images into base64, on init

**Comment by josealejandro2928** [comment]
Look this example:
![image](https://github.com/josealejandro2928/react-image-picker-editor/assets/37028825/343f91ac-0e4c-49be-98e7-3755f5c71800)
here i initialize the state with this wikipedia image, then it is passed as prop to the component:
    <p>Pick and edit an image:</p>
        < ReactImagePickerEditor
          imageSrcProp={logo as any}
          config={config2}
          imageChanged={(newDataUri: any) => { setImageSrc2(newDataUri) }} />
      </div>
      then the result:
      
![image](https://github.com/josealejandro2928/react-image-picker-editor/assets/37028825/2e2448c0-e4ef-4dfa-b9e4-dfc67798c4f5)

**Comment by BilawalSh** [comment]
Here is the simplest Script:

![image](https://github.com/josealejandro2928/react-image-picker-editor/assets/59328380/e48862d9-ad72-4032-8166-7280a4e19bbf)

Output (Error)
![image](https://github.com/josealejandro2928/react-image-picker-editor/assets/59328380/f455bf8a-6f14-4c66-bef9-0e7a70e2f3dc)

Package.json
![image](https://github.com/josealejandro2928/react-image-picker-editor/assets/59328380/7f5468be-daf3-46b6-8899-74f9ece7ef63)


what is wrong in this code

**Comment by BilawalSh** [comment]
Thank you for confirmation
