### ISSUE TITLE
Hello im having issue where the text- fonts in the editor are white so they are invisible how do i adjust the fonts colors 

### ISSUE THREAD

**Issue by Micho-github** [josealejandro2928/react-image-picker-editor#11]
i did the same as the npm provided and imported the styles but when trying to edit an image, the text-fonts are white so they are invisible how do i adjust the fonts colors for the edit inputs? 
![Screenshot 2024-03-11 195412](https://github.com/josealejandro2928/react-image-picker-editor/assets/127141643/26de4a13-1394-45a5-9c68-8f7355206e67)

**Comment by josealejandro2928** [comment]
Give more context, I think you have override the styles, but     I dont know whay you get this isse, by defauli it works like the example on the library

**Comment by josealejandro2928** [comment]
Non answer of feedback
