### ISSUE TITLE
After selected image getting image size & format by dafault, need to show image name here, there are no options to customize this.

### ISSUE THREAD

**Issue by wadenarel** [josealejandro2928/react-image-picker-editor#12]
After selected image getting image size & format by dafault, need to show image name here, there are no options to customize this.

**Comment by wadenarel** [comment]
@josealejandro2928 please response on this issues.

**Comment by josealejandro2928** [comment]
But I dont get the point, show a picture, What you mean by showing a image name ?

**Comment by wadenarel** [comment]
@josealejandro2928 any update? please

**Comment by josealejandro2928** [comment]
Hi, what you need is like to define an optional prop in which we can pass the name of the image in case of editing one otherwise the name of the selection from filesystem?.

**Comment by wadenarel** [comment]
![image](https://github.com/josealejandro2928/react-image-picker-editor/assets/139941269/bed84795-4a9c-464b-b5e1-7046c7b4a531)

@josealejandro2928 yes, i want to show image name from filesystem. please share code.

**Comment by wadenarel** [comment]
@josealejandro2928 Hi, any update? i just need to show image name.

**Comment by wadenarel** [comment]
@josealejandro2928 @Lucas-Jav Hello, any update?

**Comment by josealejandro2928** [comment]
I think you can made this, and is not a prority on the component

**Comment by josealejandro2928** [comment]
I think you can made this, and is not a prority on the component
