### ISSUE TITLE
Version 1.3.4 has dependency on react 17

### ISSUE THREAD

**Issue by ericwhitlock** [josealejandro2928/react-image-picker-editor#15]
Hi Jose. Great library. Thanks for your efforts on it.

I am running react 18.2.0 and saw that version 1.3.4 of your library shows "Ready to React 18" at https://www.npmjs.com/package/react-image-picker-editor
but after running `npm i` I ran into the following error:
```
Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from react-image-picker-editor@1.3.4
npm ERR! node_modules/react-image-picker-editor
npm ERR!   react-image-picker-editor@"^1.3.4" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2" from react-image-picker-editor@1.3.4
npm ERR!   node_modules/react-image-picker-editor
npm ERR!     react-image-picker-editor@"^1.3.4" from the root project
```
Is this due to your package.json below or am I doing something wrong? https://github.com/josealejandro2928/react-image-picker-editor/blob/6a9f18ca950b7d908c7667d7aa8fc762a8fb21ab/package.json#L30-L32

**Comment by josealejandro2928** [comment]
Closing

**Comment by josealejandro2928** [comment]
close

**Comment by UncleSamSwiss** [comment]
Can you please reopen this issue and update your package.json to support React 18.
There are multiple possibilities:
```json
 "peerDependencies": { 
   "react": ">=17.0.2" 
 },
```
or if you need at least a certain React 18 version
```json
 "peerDependencies": { 
   "react": "^17.0.2 || >=18.1.0" 
 },
```
