### ISSUE TITLE
When will it be upgraded to React 18?

### ISSUE THREAD

**Issue by AnnieTaylorCHEN** [josealejandro2928/react-image-picker-editor#2]
Would love to try this out but it has conflict with the dependencies. 😢

**Comment by josealejandro2928** [comment]
But Annie what is the issue ?

**Comment by josealejandro2928** [comment]
If you like you can leave a issue or a pr and we can solve it. I hope this package grow in the future

**Comment by josealejandro2928** [comment]
I will upgrade this now

**Comment by josealejandro2928** [comment]
Done !!

**Comment by AnnieTaylorCHEN** [comment]
Thanks! I will give it a try soon :smile_cat:
