### ISSUE TITLE
How to change Default Compression when initial `imageSrcProp` provided?

### ISSUE THREAD

**Issue by pkrinesh** [josealejandro2928/react-image-picker-editor#3]
According to the source code, Quality is aggressively set to 92 when `imageSrcProp` is provided and not be able to set via `config.compressInitial`. But for `imageSrcProps = ""` we can set quality by `config.compressInitial`.

**Comment by pkrinesh** [comment]
Yes.

**Comment by josealejandro2928** [comment]
No from the moment. The imgSrcProp only accepts the string url of the img. It's designed to support when you load a image from your backend or from the web. But you always can fork the project an provide a solution to address your problem as a PR

**Comment by Satyad146** [comment]
I have an Array of images to edit on Click of a image I need to open the image with image-editor.
but it is not working it is only pointing to the 1st clicked image regardless of the state change I am doing

**Comment by josealejandro2928** [comment]
Please provide the code to see the state management that you are performing. Without the code I cannot help you

**Comment by Satyad146** [comment]
> And what is the issue related to ?

The issue is relate to react-image-picker-editor is somehow keeping the previous state value which is given at 1st

**Comment by josealejandro2928** [comment]
Done, here in the demo it put exacly your kind of example
[https://react-image-picker-editor.surge.sh/](https://react-image-picker-editor.surge.sh/)

**Comment by josealejandro2928** [comment]
Leave a ⭐ and share it. That helps me 🚀🚀🚀
