### ISSUE TITLE
ERESOLVE Error

### ISSUE THREAD

**Issue by gitfname** [josealejandro2928/react-image-picker-editor#6]
Hi. when installing the package from npm. it gives me ERESOLVE Error.
i'm using React 18.2.0

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: agency@0.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from react-image-picker-editor@1.3.2
npm ERR! node_modules/react-image-picker-editor
npm ERR!   react-image-picker-editor@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Digiyol.com\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Digiyol.com\AppData\Local\npm-cache\_logs\2023-07-05T13_44_59_388Z-debug-0.log

**Comment by josealejandro2928** [comment]
I will fix asap
