### ISSUE TITLE
`imageSrcProp` set on load from web url but it's going in loop as I have array of Image

### ISSUE THREAD

**Issue by salmangetmee** [josealejandro2928/react-image-picker-editor#7]
hi,

there is problem of image loading again and again. Let me explain the scenario. i have a array of Object in which user can add new Object and Remove any Object. that Object has 3 properties. title, description and Icon (for Image). now we I load the Initial data if user has set them the array is looping and setting the image in `imageSrcProp` which call's the method `imageChanged` and there I am updating the state value which is causing the re-render in react. So it's just loading image again and again. 

![image](https://github.com/josealejandro2928/react-image-picker-editor/assets/141009190/e6eb57f5-166c-48cd-be46-c4ad38306e65)

This is the code it's inside map function
![image](https://github.com/josealejandro2928/react-image-picker-editor/assets/141009190/b26e40fb-0bbb-4f65-83bd-e2dd1cf48fff)

**Comment by josealejandro2928** [comment]
Trying using memo for not reseting the state on the component
